.file "vk_defs.s"

.equ KEY_RESERVED,     0
.equ KEY_ESC,          1
.equ KEY_1,            2
.equ KEY_2,            3
.equ KEY_3,            4
.equ KEY_4,            5
.equ KEY_5,            6
.equ KEY_6,            7
.equ KEY_7,            8
.equ KEY_8,            9
.equ KEY_9,            10
.equ KEY_0,            11
.equ KEY_MINUS,        12
.equ KEY_EQUAL,        13
.equ KEY_BACKSPACE,    14
.equ KEY_TAB,          15
.equ KEY_Q,            16
.equ KEY_W,            17
.equ KEY_E,            18
.equ KEY_R,            19
.equ KEY_T,            20
.equ KEY_Y,            21
.equ KEY_U,            22
.equ KEY_I,            23
.equ KEY_O,            24
.equ KEY_P,            25
.equ KEY_LEFTBRACE,    26
.equ KEY_RIGHTBRACE,   27
.equ KEY_ENTER,        28
.equ KEY_LEFTCTRL,     29
.equ KEY_A,            30
.equ KEY_S,            31
.equ KEY_D,            32
.equ KEY_F,            33
.equ KEY_G,            34
.equ KEY_H,            35
.equ KEY_J,            36
.equ KEY_K,            37
.equ KEY_L,            38
.equ KEY_SEMICOLON,    39
.equ KEY_APOSTROPHE,   40
.equ KEY_GRAVE,        41
.equ KEY_LEFTSHIFT,    42
.equ KEY_BACKSLASH,    43
.equ KEY_Z,            44
.equ KEY_X,            45
.equ KEY_C,            46
.equ KEY_V,            47
.equ KEY_B,            48
.equ KEY_N,            49
.equ KEY_M,            50
.equ KEY_COMMA,        51
.equ KEY_DOT,          52
.equ KEY_SLASH,        53
.equ KEY_RIGHTSHIFT,   54
.equ KEY_KPASTERISK,   55
.equ KEY_LEFTALT,      56
.equ KEY_SPACE,        57
.equ KEY_CAPSLOCK,     58
.equ KEY_F1,           59
.equ KEY_F2,           60
.equ KEY_F3,           61
.equ KEY_F4,           62
.equ KEY_F5,           63
.equ KEY_F6,           64
.equ KEY_F7,           65
.equ KEY_F8,           66
.equ KEY_F9,           67
.equ KEY_F10,          68
.equ KEY_NUMLOCK,      69
.equ KEY_SCROLLLOCK,   70
.equ KEY_KP7,          71
.equ KEY_KP8,          72
.equ KEY_KP9,          73
.equ KEY_KPMINUS,      74
.equ KEY_KP4,          75
.equ KEY_KP5,          76
.equ KEY_KP6,          77
.equ KEY_KPPLUS,       78
.equ KEY_KP1,          79
.equ KEY_KP2,          80
.equ KEY_KP3,          81
.equ KEY_KP0,          82
.equ KEY_KPDOT,        83
.equ KEY_F11,          87
.equ KEY_F12,          88
.equ KEY_KPENTER,      96
.equ KEY_RIGHTCTRL,    97
.equ KEY_KPSLASH,      98
.equ KEY_SYSRQ,        99
.equ KEY_RIGHTALT,     100
.equ KEY_HOME,         102
.equ KEY_UP,           103
.equ KEY_PAGEUP,       104
.equ KEY_LEFT,         105
.equ KEY_RIGHT,        106
.equ KEY_END,          107
.equ KEY_DOWN,         108
.equ KEY_PAGEDOWN,     109
.equ KEY_INSERT,       110
.equ KEY_DELETE,       111
.equ KEY_PAUSE,        119
.equ KEY_LEFTMETA,     125
.equ KEY_RIGHTMETA,    126
.equ KEY_COMPOSE,      127
